name: "Идея / Feature request"
description: "Предложение по улучшению / An idea for improvement"
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: "Идея / The idea"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "Какую задачу решает / What problem it solves"
